[book]
# Title of the book
title = "AutoPilot POAM"

# Author of the book
authors = ["Austin Songer"]

# Language of the book
language = "en"

# Directory containing markdown files
src = "my_markdown_files"  # Custom directory for markdown files

# Build output directory
build-dir = "output"

# Whether to include a search index
create-search-index = true

[output.html]
# The theme used for the HTML output
theme = "light"

# Additional options for the HTML output
default-theme = "light"
additional-js = []
additional-css = []