[book]
title = "AutoPilot: POAM"
authors = ["Austin Songer"]
language = "en"
create-search-index = true
src = "content"

[build]
build-dir = "output"
create-missing = false

[output.html]
theme = "/content/theme/default"
site-url = "/docs/"
git-repository-url = "https://github.com/austinsonger/AutoPilot"
