[book]
title = "AutoPilot: POAM"
authors = ["Austin Songer"]
language = "en"
create-search-index = true
src = "docs"

[build]
build-dir = "output"

[output.html]
theme = "theme/default"
site-url = "/docs/"

